### ISSUE TITLE
bug - Wrong --help message is shown

### ISSUE THREAD

**Issue by 59e5aaf4** [CrowdStrike/Falcon-Toolkit#47]
Hello. Looks like there's something wrong in there :D

```
C:\ops> ps --help
Usage: put_files [-h]

[macOS] Display the System Integrity Protection status.

optional arguments:
  -h, --help  show this help message and exit
```

Cheers,

**Comment by ChristopherHammond13** [comment]
Nice catch! Thank you! I'll get a branch cut to sort this out now.

**Comment by ChristopherHammond13** [comment]
Okay, this is actually even more of a bizarre issue than I thought. It turns out that one thing binds the `ps`, `put_files` and `csrutil` commands: they both use the same `blank_argparser` defined here: https://github.com/CrowdStrike/Falcon-Toolkit/blob/main/falcon_toolkit/shell/parsers.py#L22

I think what's happening here is that Cmd2 injects something additional into the Cmd2ArgumentParser() to provide the help functionality, but as the argparser is not cloned (the reference is duplicated), it is causing the help message from the first defined command, `csrutil` due to the alphabet, to be returned for other commands.

Really cool bug. Thanks for pointing it out!

**Comment by 59e5aaf4** [comment]
ha no problem, interesting indeed. Nice explanation. I sometimes have these shared reference bugs in my code as well :D
